TERMUX_PKG_HOMEPAGE=https://embree.github.io
TERMUX_PKG_DESCRIPTION="Collection of high-performance ray tracing kernels"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=3.13.5
TERMUX_PKG_SRCURL=https://github.com/embree/embree/archive/v${TERMUX_PKG_VERSION}/embree-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=b8c22d275d9128741265537c559d0ea73074adbf2f2b66b0a766ca52c52d665b
TERMUX_PKG_DEPENDS="libtbb"
TERMUX_PKG_BUILD_DEPENDS="libxmu,freeglut"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DEMBREE_TUTORIALS=OFF
-DEMBREE_MAX_ISA=AVX512SKX
-DEMBREE_RAY_MASK=ON
-DEMBREE_FILTER_FUNCTION=ON
-DEMBREE_ISPC_SUPPORT=OFF
-DEMBREE_BACKFACE_CULLING=OFF
"
